// <auto-generated />
namespace MonthlyProjectCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbmigration3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbmigration3));
        
        string IMigrationMetadata.Id
        {
            get { return "202112160503033_dbmigration3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
